name: Bunnyshell Update PR Environment
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - master
jobs:
  deploy:
    name: Deploy PR Environment
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          *Bunnyshell* Environment created with the following endpoints:
          - "https://frontend-demo-books.bunnyenv.com"
          - "https://api-demo-books.bunnyenv.com"
